# Author: Vladimir Vysokomornyi

name: Run e2e tests
description: Run Playwright E2E tests

inputs:
  username:
    description: user email
    required: true
  password:
    description: user password
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        cache: "npm"
        cache-dependency-path: code/frontend/home-expenses-ui/package-lock.json
        node-version: 20

    - name: Run e2e tests on local env
      shell: bash
      run: |
        cd code/frontend/home-expenses-ui
        npm ci
        sudo echo "127.0.0.1 local.home-expenses.com" | sudo tee -a /etc/hosts
        PLAYWRIGHT_BROWSERS=chromium npx playwright install
        npm run e2e-local:ci
      env:
        PLAYWRIGHT_USERNAME: ${{ inputs.username }}
        PLAYWRIGHT_PASSWORD: ${{ inputs.password }}

#  npx playwright install --with-deps

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: code/frontend/home-expenses-ui/playwright-report/
        retention-days: 30
