# Author: Vladimir Vysokomornyi

name: Run e2e tests
description: Run Playwright E2E tests

inputs:
  username:
    description: user email
    required: true
  password:
    description: user password
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        cache: "npm"
        cache-dependency-path: code/frontend/home-expenses-ui/package-lock.json
        node-version: 20

    - name: Run e2e tests
      shell: bash
      run: |
        cd code/frontend/home-expenses-ui
        npm ci
        npx playwright install --with-deps
        npm run e2e -- login.spec.ts
      env:
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
