name: Close Issue

on:
  project_card:
    types: [moved]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        if: startsWith(github.event.project_card.note, 'automove') && github.event.project_card.column_name == 'Done'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Project card:', project_card);
#            const { project_card } = context.payload;
#            const columnName = project_card.column_name;
#            const issueUrl = project_card.content_url;
#
#            // Check if the card is moved to the "Done" column
#            if (columnName === 'Done') {
#              // Close the associated issue
#              await github.issues.update({
#                issue_number: context.payload.issue.id,
#                state: 'closed'
#              });
#            }
