name: Close Issue

on:
  issues:
    types: [opened, edited, milestoned]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: print some details
        shell: bash
        run: |
          echo "Issue Event: ${{ github.event_name }}"
          echo "Issue Action: ${{ github.event.action }}"
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue State: ${{ github.event.issue.state }}"
          echo "Issue Assignee: ${{ github.event.issue.assignee.login }}"
          echo "Issue Labels: ${{ join(github.event.issue.labels.*.name, ', ') }}"
          echo "Issue Milestone: ${{ github.event.issue.milestone.title }}"

      - name: Close Issue
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Project card:', project_card);
#            const { project_card } = context.payload;
#            const columnName = project_card.column_name;
#            const issueUrl = project_card.content_url;
#
#            // Check if the card is moved to the "Done" column
#            if (columnName === 'Done') {
#              // Close the associated issue
#              await github.issues.update({
#                issue_number: context.payload.issue.id,
#                state: 'closed'
#              });
#            }


# if: startsWith(github.event.project_card.note, 'automove') && github.event.project_card.column_name == 'Done'