# Author: Vladimir Vysokomornyi

name: Display secret

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  node-version: 20

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}

      - name: Display secrets
        shell: bash
        run: |
          echo "UI_URL '${{ secrets.UI_URL }}'."
          node decode_secret.js
