# Author: Vladimir Vysokomornyi

name: Display secret

on:
  workflow_dispatch:
    inputs:
      secretName:
        type: string
        required: true
        description: Put secret name

permissions:
  id-token: write
  contents: read

env:
  node-version: 20

jobs:
  displaySecret:
    runs-on: ubuntu-latest
    environment: dev

    steps:
#      - uses: actions/checkout@v4

      - name: Display repo secret
        shell: bash
        run: |
          echo Secret name: ${{ github.event.inputs.secretName }}, value
#          echo Secret name: ${{ github.event.inputs.secretName }}, value: ${{ secrets.${{ github.event.inputs.secretName }} }} | sed 's/./& /g'
#          echo ${{ secrets.UI_URL }} | sed 's/./& /g'

#          echo ${{ secrets.AUTH_AT_SECRET }} | sed 's/./& /g'
#          echo ${{ secrets.AUTH_RT_SECRET }} | sed 's/./& /g'
