# Author: Vladimir Vysokomornyi

name: Display secret

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  node-version: 20

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Display secrets
        shell: bash
        run: |
          echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'
          encoded_value=$(echo "${{ secrets.TEST_SECRET }}" | base64)
          echo "encoded: $encoded_value"
          decoded_value=$(echo "$encoded_value" | base64 --decode)
          echo "decoded: $decoded_value"

