# Author: Vladimir Vysokomornyi

name: Display secret

on:
  workflow_dispatch:
    inputs:
      secretName:
        type: string
        required: true
        description: Put secret name

permissions:
  id-token: write
  contents: read

env:
  node-version: 20

jobs:
  displaySecret:
    runs-on: ubuntu-latest
    environment: dev

    steps:
#      - uses: actions/checkout@v4

      - name: Display repo secret
        shell: bash
        env:
          SECRET_NAME: ${{ github.event.inputs.secretName }}
        run: |
          echo "${{ env.SECRET_NAME }}: [$(echo ${{ secrets[env.SECRET_NAME] }} | sed 's/./& /g')]"
