# Author: Vladimir Vysokomornyi

name: Display secret

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  node-version: 20

jobs:
  displaySecret:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Display repo secret
        shell: bash
        run: |
          echo ${{ secrets.AUTH_AT_SECRET }} | sed 's/./& /g'
          echo ${{ secrets.AUTH_RT_SECRET }} | sed 's/./& /g'
