# Author: Vladimir Vysokomornyi

name: Display secret

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  node-version: 20

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Display secrets
        shell: bash
        run: |
          echo ${{ secrets.UI_URL }} | sed 's/./& /g'

