# Author: Vladimir Vysokomornyi

name: Display secret

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  node-version: 20

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Display repo secret
        shell: bash
        run: |
          echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'
          encoded_value=$(echo "${{ secrets.TEST_SECRET }}" | base64)
          echo "encoded repo secret: $encoded_value"
          echo ${{ secrets.TEST_SECRET2 }} | sed 's/./& /g'

      - name: Display env secret
        shell: bash
        run: |
          echo ${{ secrets.TEST_SECRET2 }} | sed 's/./& /g'
          
