# Author: Vladimir Vysokomornyi

name: Display secret

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  node-version: 20

jobs:
  disoplaySecret:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v4

      - name: Display repo secret
        shell: bash
        run: |
          echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'
          encoded_value=$(echo "${{ secrets.TEST_SECRET }}" | base64)
          echo "encoded repo secret: $encoded_value"

      - name: Display env secret
        shell: bash
        run: |
          echo ${{ secrets.TEST_SECRET2 }} | sed 's/./& /g'
          encoded_value=$(echo "${{ secrets.TEST_SECRET2 }}" | base64)
          echo "encoded repo secret: $encoded_value"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependency
        shell: bash
        run: |
          pip install base64
          pip install nacl

      - name: Run Python
        shell: python
        run: |
          from base64 import b64encode
          from nacl import encoding, public

          def encrypt(public_key: str, secret_value: str) -> str:
            """Encrypt a Unicode string using the public key."""
            public_key = public.PublicKey(public_key.encode("utf-8"), encoding.Base64Encoder())
            sealed_box = public.SealedBox(public_key)
            encrypted = sealed_box.encrypt(secret_value.encode("utf-8"))
            return b64encode(encrypted).decode("utf-8")
            
            encrypt("YOUR_BASE64_KEY", "YOUR_SECRET")
