# Author: Vladimir Vysokomornyi

name: Display secret

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  node-version: 20

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Display secrets
        shell: bash
        run: |
          echo "UI_URL '${{ secrets.UI_URL }}'."
          echo "DB_PORT '${{ secrets.DB_PORT }}'."
