# Author: Vladimir Vysokomornyi

name: Run E2E tests Manual

on:
# Runs every day at 0:10 AM UTC
#  schedule:
#    - cron: '10 0 * * *'

  workflow_dispatch:
    inputs:
      local:
        type: choice
        description: Should we run LOCAL e2e tests
        required: true
        default: 'false'
        options:
          - 'true'
          - 'false'
      dev:
        type: choice
        description: Should we run DEV e2e tests
        required: true
        default: 'true'
        options:
          - 'true'
          - 'false'

env:
  node-version: 20

jobs:
  e2e_tests_local:
    name: Run E2E tests for local
    if: github.event.inputs.local == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Playwright E2E tests for LOCAL env
        uses: ./.github/actions/run-e2e-local-tests
        with:
          username: ${{ secrets.PLAYWRIGHT_USERNAME }}
          password: ${{ secrets.PLAYWRIGHT_PASSWORD }}

  e2e_tests_dev:
    name: Run E2E tests for dev
    if: github.event.inputs.dev == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Playwright E2E tests for DEV env
        uses: ./.github/actions/run-e2e-env-tests
        with:
          username: ${{ secrets.PLAYWRIGHT_USERNAME }}
          password: ${{ secrets.PLAYWRIGHT_PASSWORD }}
          envInstance: dev

