# Author: Vladimir Vysokomornyi

name: Run E2E tests

on:
#  push:
#    branches: ["main"]
  workflow_dispatch:
    inputs:
      local:
        type: choice
        description: Should we run LOCAL e2e tests
        required: true
        default: true
        options:
          - 'true'
          - 'false'
      dev:
        type: choice
        description: Should we run DEV e2e tests
        required: true
        default: false
        options:
          - 'true'
          - 'false'

env:
  node-version: 20

jobs:
  e2e_tests:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Playwright E2E tests for LOCAL env
        if: github.event.inputs.local == 'true'
        uses: ./.github/actions/run-e2e-local-tests
        with:
          username: ${{ secrets.PLAYWRIGHT_USERNAME }}
          password: ${{ secrets.PLAYWRIGHT_PASSWORD }}

      - name: Run Playwright E2E tests for DEV env
        if: github.event.inputs.dev == 'true'
        uses: ./.github/actions/run-e2e-dev-tests
        with:
          username: ${{ secrets.PLAYWRIGHT_USERNAME }}
          password: ${{ secrets.PLAYWRIGHT_PASSWORD }}
          envInstance: dev

