# Author: Vladimir Vysokomornyi

name: Run E2E tests each 30 minutes

on:
# Runs every day at X:30
  schedule:
    - cron: '30 * * * *'

env:
  node-version: 20

jobs:
  dev_e2e:
    name: Run E2E tests for dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Playwright E2E tests for DEV env
        uses: ./.github/actions/run-e2e-env-tests
        with:
          username: ${{ secrets.PLAYWRIGHT_USERNAME }}
          password: ${{ secrets.PLAYWRIGHT_PASSWORD }}
          envInstance: dev
