name: Rotate access and refresh tokens

on:
  # Runs every Sunday at 5:00 AM UTC
  schedule:
    - cron: '0 5 * * 0'

  workflow_dispatch:

jobs:
  update_tokens:
    name: Update access and refresh tokens
    runs-on: ubuntu-20.04
    steps:
#      - name: Checkout
#        uses: actions/checkout@v4

#      - name: Get Public Key
#        run: |
#          curl -X GET \
#            -H "Accept: application/vnd.github+json" \
#            -H "Authorization: Bearer $ACCESS_TOKEN" \
#            -H "X-GitHub-Api-Version: 2022-11-28" \
#            https://api.github.com/repos/unlimit1984/home-expenses/actions/secrets/public-key
#        env:
#          ACCESS_TOKEN: ${{ secrets.GH_PAT_SECRETS }}

      - name: Get and save Public Key
        id: getPublicKeyId
        run: |
          public_key_info=$(curl -X GET \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/unlimit1984/home-expenses/actions/secrets/public-key)
          echo "$public_key_info" | jq -r '.key_id'
          echo repoKeyId="$public_key_info" | jq -r '.key_id'  >> $GITHUB_OUTPUT
        env:
          ACCESS_TOKEN: ${{ secrets.GH_PAT_SECRETS }}

#          echo repoKeyId=$public_key_info >> $GITHUB_OUTPUT

      - name: Print repo public key
        run: |
          echo "Repo public keyId: ${{ steps.getPublicKeyId.outputs.repoKeyId }}"
#          echo "Repo public key: ${{ steps.getPublicKeyId.outputs.repoKeyId }}"
#          key_id=$(echo "${{ steps.getPublicKeyId.outputs.repoKeyId }}" | jq -r '.key_id')
#          echo "repo key id: $key_id"
#          echo keyId=$key_id >> $GITHUB_ENV

#      - name: Print secret before update
#        run: |
#          echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'
#
#      - name: Update Secret
#        run: |
#          newValEncoded=$(echo "789" | base64)
#
#          curl -X PUT \
#            -H "Authorization: Bearer ${{ secrets.GH_PAT_SECRETS }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            -d '{"encrypted_value":"$newValEncoded","key_id":"${{ env.keyId }}"}' \
#            https://api.github.com/repos/unlimit1984/home-expenses/actions/secrets/TEST_SECRET
#
#      - name: Print secret after update
#        run: |
#          echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'
