name: Rotate access and refresh tokens

on:
  # Runs every Sunday at 5:00 AM UTC
  schedule:
    - cron: '0 5 * * 0'

  workflow_dispatch:

jobs:
  update_tokens:
    name: Update access and refresh tokens
    runs-on: ubuntu-20.04
    steps:
#      - name: Checkout
#        uses: actions/checkout@v4

      - name: Get Public Key
        id: getPublicKeyId
        run: |
          curl -L GET \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GH_PAT_SECRETS }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/unlimit1984/home-expenses/actions/secrets/public-key
#        env:
#          ACCESS_TOKEN: ${{ secrets.GH_PAT_SECRETS }}

#            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \ ${{ secrets.GH_PAT_SECRETS }}
#            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
#            -u ${{ secrets.ACCESS_TOKEN }} \
#            -H "Authorization: Bearer ${{ secrets.GH_PAT_SECRETS }}" \

#      - name: Get Public Key
#        id: getPublicKeyId
#        run: |
#          public_key_info=$(curl -X GET \
#            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            https://api.github.com/repos/unlimit1984/home-expenses/actions/secrets/public-key)
#          echo repoKeyId=$public_key_info >> $GITHUB_OUTPUT
#        env:
#          ACCESS_TOKEN: ${{ secrets.GH_PAT_SECRETS }}
#
#      - name: Print repo public key
#        run: |
#          echo "Repo public key: ${{ steps.getPublicKeyId.outputs.repoKeyId }}"

#      - name: Update Secret
#        run: |
#          curl -X PUT \
#            -H "Authorization: token ${{ secrets.PAT }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            -d '{"encrypted_value":"base64_encoded_value","key_id":"key_id"}' \
#            https://api.github.com/repos/:owner/:repo/actions/secrets/YOUR_SECRET_NAME
#        env:
#          YOUR_SECRET_NAME: <your_secret_name>