name: Rotate access and refresh tokens

on:
  # Runs every Sunday at 5:00 AM UTC
#  schedule:
#    - cron: '0 5 * * 0'

  # Runs every day at 0:00 AM UTC
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  update_tokens:
    name: Update access and refresh tokens
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get and save Public Key
        id: getPublicKeyId
        run: |
          public_key_info=$(curl -X GET \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/unlimit1984/home-expenses/actions/secrets/public-key)
          
          keyId=$(echo "$public_key_info" | jq -r '.key_id')
          echo "::add-mask::$keyId"        
          echo repoKeyId="$keyId" >> $GITHUB_OUTPUT
          
          key=$(echo "$public_key_info" | jq -r '.key')
          echo "::add-mask::$key"
          echo repoKey="$key" >> $GITHUB_OUTPUT
        env:
          ACCESS_TOKEN: ${{ secrets.GH_PAT_SECRETS }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate secret
        run: |
          secretValue=$(node ./code/js_files/generate_secret_value.js)
          echo "::add-mask::$secretValue"
          echo secretValue=$secretValue >> $GITHUB_ENV

      - name: Encrypt new secret via libsodium lib
        run: |
          npm i libsodium-wrappers
          encryptedSecretValue=$(node ./code/js_files/get_encrypted_secret.js ${{ env.secretValue}} ${{ steps.getPublicKeyId.outputs.repoKey }})
          echo "::add-mask::$encryptedSecretValue"
          echo encryptedSecretValue=$encryptedSecretValue >> $GITHUB_ENV

      - name: Update Secret
        run: |
          curl -X PUT \
            -H 'Authorization: Bearer ${{ secrets.GH_PAT_SECRETS }}' \
            -H 'X-GitHub-Api-Version: 2022-11-28' \
            -H 'Accept: application/vnd.github+json' \
            -d '{"encrypted_value":"${{ env.encryptedSecretValue}}","key_id":"${{ steps.getPublicKeyId.outputs.repoKeyId }}"}' \
            https://api.github.com/repos/unlimit1984/home-expenses/actions/secrets/TEST_SECRET
