name: Rotate access and refresh tokens

on:
  # Runs every Sunday at 5:00 AM UTC
  schedule:
    - cron: '0 5 * * 0'

  workflow_dispatch:

jobs:
  update_tokens:
    name: Update access and refresh tokens
    runs-on: ubuntu-20.04
    steps:
#      - name: Checkout
#        uses: actions/checkout@v4

#      - name: Get Public Key
#        run: |
#          curl -X GET \
#            -H "Accept: application/vnd.github+json" \
#            -H "Authorization: Bearer $ACCESS_TOKEN" \
#            -H "X-GitHub-Api-Version: 2022-11-28" \
#            https://api.github.com/repos/unlimit1984/home-expenses/actions/secrets/public-key
#        env:
#          ACCESS_TOKEN: ${{ secrets.GH_PAT_SECRETS }}

      - name: Get and save Public Key
        id: getPublicKeyId
        run: |
          public_key_info=$(curl -X GET \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/unlimit1984/home-expenses/actions/secrets/public-key)
          keyId=$(echo "$public_key_info" | jq -r '.key_id')
          key=$(echo "$public_key_info" | jq -r '.key')
          echo repoKeyId="$keyId" >> $GITHUB_OUTPUT
          echo repoKey="$key" >> $GITHUB_OUTPUT
        env:
          ACCESS_TOKEN: ${{ secrets.GH_PAT_SECRETS }}

      - name: Print repo public key
        run: |
          echo "Repo public keyId: ${{ steps.getPublicKeyId.outputs.repoKeyId }}"
          echo "Repo public key: ${{ steps.getPublicKeyId.outputs.repoKey }}"

      - name: Print secret before update
        run: |
          echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run javascript
        run: |
          node --version
          ls -la
#          node ./code/js_files/hello_script.js

#      - name: Generate new token secret
#        run: |
#          echo newValEncoded=$(echo "789" | base64) >> $GITHUB_ENV


#      - name: Update Secret
#        run: |
#          echo $newValEncoded
#          echo ${{ env.newValEncoded }}
#
#          curl -X PUT \
#            -H "Authorization: Bearer ${{ secrets.GH_PAT_SECRETS }}" \
#            -H "Accept: application/vnd.github.v3+json" \
#            -d '{"encrypted_value":"${{ env.newValEncoded }}","key_id":"${{ steps.getPublicKeyId.outputs.repoKeyId }}"}' \
#            https://api.github.com/repos/unlimit1984/home-expenses/actions/secrets/TEST_SECRET
#
#      - name: Print secret after update
#        run: |
#          echo ${{ secrets.TEST_SECRET }} | sed 's/./& /g'
